server:
  port: 8081
  
spring:
  application:
    name: 'fornecedor'
  datasource:
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}